const Constants = {
  ASSIGNED_CUSTOMERS: "ASSIGNED_CUSTOMERS",
  ASSIGNED_PRODUCTS: "ASSIGNED_PRODUCTS",
  PRODUCTS: "products",
  SOLINAS: "solinas",
  CUSTOMER_ID: "CUSID",
  CUSTOMER_NAME: "CUSNAME",
  TEMPORARY_CUSTOMER_ID: "TEMP_CUSID",
  X_SWASTH_CUST_ID: "X-SWASTH-CUST-ID",
  INSPECTION_ID: "IID",
  COMPLETED_IN: "COMPIID"
};

export default Constants;
