# Use an official Node.js 22 image for building
FROM node:22-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy only package.json and package-lock.json first for better caching
COPY package*.json ./

# Install dependencies with a clean environment
RUN npm install -g env-cmd
RUN npm install --frozen-lockfile

# Copy the rest of the application
COPY . .

# Build the Next.js application
RUN npm run build-prod

# Use a smaller Node.js 22 image for production
FROM node:22-alpine AS runner

# Set a non-root user for security
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Set the working directory
WORKDIR /app

RUN npm install -g env-cmd

# Copy necessary files from the builder stage
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.env.production ./.env.production


# Change ownership of files
RUN chown -R appuser:appgroup /app

# Expose the port the app will run on
EXPOSE 3000

# Switch to the non-root user
USER appuser

# Set the default command to start the application
CMD ["npm", "run", "start-prod"]
