import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex w-full gap-4 h-screen`}
      >
        <div className="w-[20vw] bg-white h-full flex flex-col gap-2 rounded-md text-black p-4">
          <Link href="/" className="bg-gray-500 p-2 rounded-md w-full">
            Dashboard
          </Link>
          <Link
            href="/inspections"
            className="bg-gray-500 p-2 rounded-md w-full"
          >
            Inspections
          </Link>
          <Link href="/map" className="bg-gray-500 p-2 rounded-md w-full">
            Map
          </Link>
        </div>
        <div className="w-[80vw]">{children}</div>
      </body>
    </html>
  );
}
